import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ko">
      <body className="min-h-screen flex flex-col">
        {/* 공통 헤더: 404 페이지가 떠도 이 영역은 무너지지 않습니다! */}
        <nav className="h-16 bg-white border-b flex items-center justify-between px-8 sticky top-0 z-50">
          <Link
            href="/"
            className="text-xl font-black text-indigo-600 tracking-tighter"
          >
            TechNova.
          </Link>
          <div className="flex gap-6 text-sm font-bold text-gray-500">
            <Link href="/" className="hover:text-indigo-600 transition">
              Home
            </Link>
            <Link href="/products" className="hover:text-indigo-600 transition">
              Products
            </Link>
            <Link
              href="/dashboard"
              className="hover:text-emerald-400 transition-colors"
            >
              Dashboard
            </Link>
          </div>
          <div className="flex gap-6 text-sm font-bold text-gray-500">
            <span className="text-2xl font-black text-red-600 tracking-tighter uppercase italic">
              StreamFlix.
            </span>
            <Link href="/movies" className="hover:text-indigo-600 transition">
              Products
            </Link>
          </div>
        </nav>
        {/* 실제 페이지 콘텐츠 및 404 페이지가 들어갈 자리 */}
        <main className="flex-1 flex flex-col">{children}</main>
        <footer className="py-6 bg-slate-900 text-slate-400 text-center text-xs">
          © 2026 TechNova Inc. All Rights Reserved.
        </footer>
      </body>
    </html>
  );
}
