import type { Metadata } from "next";
import SideBar from "../components/side-bar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        {/* <AnnounceBar /> */}
        <SideBar />
        {children}
      </body>
    </html>
  );
}
